edit yml file

diff --git a/.github/workflows/lichess-data-pipeline.yml b/.github/workflows/lichess-data-pipeline.yml
--- a/.github/workflows/lichess-data-pipeline.yml
+++ b/.github/workflows/lichess-data-pipeline.yml
@@ -34,7 +34,7 @@ jobs:
           git config --list 
           echo "Setting Git user name and email....."
           if (!(git config user.name 'github-actions')) { Write-Error "Failed to set user.name"; exit 1 }
-          if (!(git config user.email 'github-actions@github.com')) || { Write-Error "Failed to set user.email"; exit 1}
+          if (!(git config user.email 'github-actions@github.com')) { Write-Error "Failed to set user.email"; exit 1}
           echo "Adding changes....."
           git add .
           echo "Checking for changes....."
