edit yml file

diff --git a/.github/workflows/lichess-data-pipeline.yml b/.github/workflows/lichess-data-pipeline.yml
--- a/.github/workflows/lichess-data-pipeline.yml
+++ b/.github/workflows/lichess-data-pipeline.yml
@@ -33,12 +33,15 @@ jobs:
           echo "Git config list:"
           git config --list 
           echo "Setting Git user name and email....."
-          if (!(git config user.name 'github-actions')) { Write-Error "Failed to set user.name"; exit 1 }
-          if (!(git config user.email 'github-actions@github.com')) { Write-Error "Failed to set user.email"; exit 1}
+          git config user.name 'github-actions' || { Write-Error "Failed to set user.name"; exit 1 }
+          git config user.email 'github-actions@github.com'|| { Write-Error "Failed to set user.email"; exit 1}
           echo "Adding changes....."
           git add .
           echo "Checking for changes....."
-          if (git diff --staged --quiet) { echp "No changes detected"}   else { echo "changes=true" >> $env:GITHUB_ENV }
+          git diff --staged --quiet || echo "changes=true" >> $env:GITHUB_ENV 
+          if (!(Test-Path -Path env:GITHUB_ENV)){ 
+            echp "No changes detected"
+          } 
       - name: Commit and push if changes
         if: env.changes == 'true' # if changes made, push data to repo
         run: |
